server:
  port: 8585
  address: 127.0.0.1
  tomcat:
    connection-timeout: 5s
    max-threads: 200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
jwt:
  secret: secret
  expiration: 3600


